# Generated by Django 4.2.4 on 2023-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('conference', 'Conference'), ('webinar', 'Webinar'), ('meetup', 'Meetup')], default='conference', max_length=20),
        ),
    ]
